version: "3"
services:
  custom-rabbitmq-broker:
    build:
      context: ./message-brokers/rabbitmq
    ports: 
      - "5672:5672"

networks:
  default:
    external:
      name: messaging-poc-network




      