spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      host: localhost
      port: 27017
      database: events_db

jackson:
  serialization:
    write_dates_as_timestamps: false


# TODO add message brokers configs here
